---
title: "Viz2 Basic Plots"
author: "Hayden Ginman"
date: "2023-09-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo =FALSE)
```

```{r code0, echo=FALSE, message=FALSE}
#Step 1 - Load libraries into coding environment
options(repos = c(CRAN = "https://cloud.r-project.org/"))
#install.packages("lubridate")
#install.packages("viridis")
library("dplyr")
library("reshape2")
library("ggplot2")
library("lubridate")
library("viridis")

```



```{r code1, echo=FALSE}
#Step 2 - Load clean data into coding environment 
#Use lubridate to convert character dates to functional format 
#Create a new column (Month) that contains the month and year of the StartDate Column

vaccinations <- read.csv("COVID-19_Vaccinations_by_Age_(Maricopa_County).csv")

vaccinations$StartDate <- as.Date(substr(vaccinations$StartDate, 1, 10), format="%Y/%m/%d")
vaccinations$Month <- format(vaccinations$StartDate, "%Y-%m")


```


```{r code2, echo=FALSE}
#Step 3 - Group the data frame by month and the sum up vaccinations for each age group

monthly_vaccinations <- vaccinations %>%
  group_by(Month) %>%
  summarize(
    Age0To14 = sum(VaccinatedAge0To14, na.rm = TRUE),
    Age15To24 = sum(VaccinatedAge15To24, na.rm = TRUE),
    Age25To34 = sum(VaccinatedAge25To34, na.rm = TRUE),
    Age35To44 = sum(VaccinatedAge35To44, na.rm = TRUE),
    Age45To54 = sum(VaccinatedAge45To54, na.rm = TRUE),
    Age55To64 = sum(VaccinatedAge55To64, na.rm = TRUE),
    Age65To74 = sum(VaccinatedAge65To74, na.rm = TRUE),
    Age75Up = sum(VaccinatedAge75Up, na.rm = TRUE)
  )

```

```{r code3, echo=FALSE}
#Step 4 - melt data from wide format to long format so each row represents a month/age group combination
#Convert month column to date format
#Create vector of age_labels that are properly formatted for legend

melt_monthly_vax <- melt(monthly_vaccinations, id.vars = "Month")

melt_monthly_vax$Month <- as.Date(paste0(melt_monthly_vax$Month, "-01"), format="%Y-%m-%d")

age_labels <- c(
  Age0To14 = "0-14 years",
  Age15To24 = "15-24 years",
  Age25To34 = "25-34 years",
  Age35To44 = "35-44 years",
  Age45To54 = "45-54 years",
  Age55To64 = "55-64 years",
  Age65To74 = "65-74 years",
  Age75Up = "75+ years"
)
```
```{r code4, echo=FALSE}
#Step 5 - Make a stacked are chart as the pretty plot

pretty_plot <- ggplot(melt_monthly_vax, aes(x = Month, y = value, fill = variable, group = variable)) +
  geom_area(position = "stack", alpha = 0.7) +
  labs(title = "Total Monthly Vaccinations in Maricopa County by Age Group",
       x = "Month",
       y = "Total Monthly Vaccinations",
       fill = "Age Group") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  scale_y_continuous(breaks = seq(0, 30000000, by = 2000000), labels = function(x) format(x, big.mark = ",", scientific = FALSE)) + 
  scale_fill_viridis_d(breaks = names(age_labels), labels = age_labels) + 
  theme_minimal()

print(pretty_plot)

```
Figure 1: Stacked area chart illustrating the month-by-month distribution of total vaccinations by age group in Maricopa County from June 2021 to February 2022. Each color represents a distinct age group, and the height of the stack indicates the cumulative number of vaccinations for the respective month.

\newpage



```{r code5, echo=FALSE, warning=FALSE}
#Step 6 - Create ugly plot with typos, useless caption, scale issues, an unsightly palette, 
#misaligned text, and small font

ugly_plot <- ggplot(melt_monthly_vax, aes(x = Month, y = value, color = variable, group = variable)) +
  geom_line() +
  labs(title = "Manthly Vaccinashuns in Maricopa Countyy by Age Groop", x = "Munth",
       y = "No. of Vaccinatons",
       color = "Age Groop", 
       caption = "Data sourc: Somewhere in Maricopa\nNote: I'm ugly :(") +
  scale_y_continuous(breaks = seq(0, max(melt_monthly_vax$value, na.rm = TRUE), by = 1e7), 
                     labels = function(x) format(x, big.mark = ".", scientific = TRUE)) + 
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y") + 
  scale_color_brewer(palette="OrRd") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0, size = 6), 
    axis.title = element_text(size = 6), 
    legend.position = "bottom", 
    legend.title = element_text(hjust = 1), 
    plot.caption = element_text(hjust = 1, color = "red"))

print(ugly_plot)

```



```{r code0, eval=FALSE, echo=TRUE}
```
```{r code1, eval=FALSE, echo=TRUE}
```
```{r code2, eval=FALSE, echo=TRUE}
```
```{r code3, eval=FALSE, echo=TRUE}
```
```{r code4, eval=FALSE, echo=TRUE}
```
```{r code5, eval=FALSE, echo=TRUE}
```